// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using data.Context;

#nullable disable

namespace data.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20250826102955_new")]
    partial class @new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("domain.Models.Comment", b =>
                {
                    b.Property<Guid>("IdComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FK_Compte")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FK_Movie")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdComment");

                    b.HasIndex("FK_Compte");

                    b.HasIndex("FK_Movie");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("domain.Models.Compte", b =>
                {
                    b.Property<Guid>("IdCompte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CIN")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FK_Role")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motdepasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("access")
                        .HasColumnType("bit");

                    b.HasKey("IdCompte");

                    b.HasIndex("FK_Role");

                    b.ToTable("Compte");
                });

            modelBuilder.Entity("domain.Models.Genre", b =>
                {
                    b.Property<Guid>("IdGenre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MovieIdMovie")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGenre");

                    b.HasIndex("MovieIdMovie");

                    b.ToTable("Genre");
                });

            modelBuilder.Entity("domain.Models.Like", b =>
                {
                    b.Property<Guid>("IdLike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FK_Compte")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FK_Movie")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdLike");

                    b.HasIndex("FK_Compte");

                    b.HasIndex("FK_Movie");

                    b.ToTable("Like");
                });

            modelBuilder.Entity("domain.Models.Movie", b =>
                {
                    b.Property<Guid>("IdMovie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("AverageRating")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FK_Compte")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MovieApiId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMovie");

                    b.HasIndex("FK_Compte");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("domain.Models.MovieGenre", b =>
                {
                    b.Property<Guid>("IdMovie")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdGenre")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdMovie", "IdGenre");

                    b.HasIndex("IdGenre");

                    b.ToTable("MovieGenre");
                });

            modelBuilder.Entity("domain.Models.Rating", b =>
                {
                    b.Property<Guid>("IdRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FK_Compte")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FK_Movie")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RatingValue")
                        .HasColumnType("int");

                    b.HasKey("IdRating");

                    b.HasIndex("FK_Compte");

                    b.HasIndex("FK_Movie");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("domain.Models.Role", b =>
                {
                    b.Property<Guid>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRole");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("domain.Models.Comment", b =>
                {
                    b.HasOne("domain.Models.Compte", "Compte")
                        .WithMany("Comments")
                        .HasForeignKey("FK_Compte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("domain.Models.Movie", "Movie")
                        .WithMany("Comments")
                        .HasForeignKey("FK_Movie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("domain.Models.Compte", b =>
                {
                    b.HasOne("domain.Models.Role", "Role")
                        .WithMany("Comptes")
                        .HasForeignKey("FK_Role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("domain.Models.Genre", b =>
                {
                    b.HasOne("domain.Models.Movie", null)
                        .WithMany("Genres")
                        .HasForeignKey("MovieIdMovie");
                });

            modelBuilder.Entity("domain.Models.Like", b =>
                {
                    b.HasOne("domain.Models.Compte", "Compte")
                        .WithMany("Likes")
                        .HasForeignKey("FK_Compte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("domain.Models.Movie", "Movie")
                        .WithMany("Likes")
                        .HasForeignKey("FK_Movie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("domain.Models.Movie", b =>
                {
                    b.HasOne("domain.Models.Compte", "Compte")
                        .WithMany("Movies")
                        .HasForeignKey("FK_Compte")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Compte");
                });

            modelBuilder.Entity("domain.Models.MovieGenre", b =>
                {
                    b.HasOne("domain.Models.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("IdGenre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("domain.Models.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("IdMovie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("domain.Models.Rating", b =>
                {
                    b.HasOne("domain.Models.Compte", "Compte")
                        .WithMany("Ratings")
                        .HasForeignKey("FK_Compte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("domain.Models.Movie", "Movie")
                        .WithMany("Ratings")
                        .HasForeignKey("FK_Movie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("domain.Models.Compte", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("Movies");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("domain.Models.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("domain.Models.Movie", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Genres");

                    b.Navigation("Likes");

                    b.Navigation("MovieGenres");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("domain.Models.Role", b =>
                {
                    b.Navigation("Comptes");
                });
#pragma warning restore 612, 618
        }
    }
}
